# Generated by Django 3.0.7 on 2020-06-29 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='customer_acct_balace',
            new_name='customer_acct_balance',
        ),
    ]
