# Generated by Django 3.0.7 on 2020-06-30 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_api', '0002_auto_20200629_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='highlighted',
        ),
    ]
